### ISSUE TITLE
关于PowerfulShell的小问题

### ISSUE THREAD

**Issue by amethyst6174** [USTC-Hackergame/hackergame2024-writeups#19]
*问题有些愚蠢，还请见谅qwq*

![image](https://github.com/user-attachments/assets/4cd30343-0d20-4d81-9be5-f86b7a884e52)
当我通过nc/网页终端链接时，ctrl+d执行后出现这样“卡死”的现象

我不太理解其中的原理，是与docker的设置有关吗？
能否简单说明一下，感谢

**Comment by Mother-Ship** [comment]
为什么要用ctrl+d执行（

**Comment by lbr77** [comment]
Ctrl-D 发送的是 EOF 信号，告诉程序输入截止了，所以程序会停止响应你的请求。

**Comment by amethyst6174** [comment]
我原本的理解是，ctrl d能正常触发`echo "EOF detected, exiting..."`，在自己的机器上测试也是这样的
![image](https://github.com/user-attachments/assets/2a91ac17-ec46-4d57-8b9f-54639b4cfd8d)
所以没想明白为什么会这样

**Comment by taoky** [comment]
按下 Ctrl + D（EOF）之后，`netcat` 是否会 shutdown TCP 的发送端取决于实现（TCP 是全双工的，因此可以只关闭发送端或者接收端）。

对于 OpenBSD Netcat 来说，需要添加 `-N` 参数：

```
       -N      shutdown(2) the network socket after EOF on the input.   Some
               servers require this to finish their work.
```

例子：

```console
> nc -N localhost 12554
Please input your token:
(replace with your token)
PowerfulShell@hackergame> EOF detected, exiting...

(Environment exited with return code 0)
^C
```
