### ISSUE TITLE
“旅行照片4.0 问题6” 答案到底是CRH6F-A还是CRH6A-A（

### ISSUE THREAD

**Issue by Momoko-Ayase** [USTC-Hackergame/hackergame2024-writeups#2]
https://github.com/USTC-Hackergame/hackergame2024-writeups/blob/master/official/%E6%97%85%E8%A1%8C%E7%85%A7%E7%89%87%204.0/README.md#%E9%97%AE%E9%A2%98-56---%E5%B0%A4%E5%85%B6%E6%98%AF%E4%BD%A0%E6%89%8D%E6%98%AF%E6%9C%80%E8%AF%A5%E5%A4%9A%E7%BB%83%E4%B9%A0%E7%9A%84%E4%BA%BA

> 或者在 Google 的搜索中也能找到「CRH6A-A」的身影
>
> ![](https://github.com/USTC-Hackergame/hackergame2024-writeups/raw/master/official/%E6%97%85%E8%A1%8C%E7%85%A7%E7%89%87%204.0/photos/CRH6A-A.png)
>
> 那么第二问的答案得到了，第一问呢？这个时候就是前半句提示语，「标志性的」，搜索 CRH6A-A 的 Wikipeida 页面：
>
> https://zh.wikipedia.org/wiki/%E5%92%8C%E8%B0%90%E5%8F%B7CRH6%E5%9E%8B%E7%94%B5%E5%8A%9B%E5%8A%A8%E8%BD%A6%E7%BB%84

总有种写官方题解的人还在认为答案是CRH6A-A的感觉（

**Comment by tiankaima** [comment]
草，写 wp 的时候头脑不太清醒，我来改下

**Comment by tiankaima** [comment]
Closed with #4
